// Mazo de canciones. Formato: [titulo, artista, año de lanzamiento original, mazo]
// mazo: "int" = internacional, "es" = español / latino
// El AÑO viene de aquí, NUNCA de Spotify (los remasters mienten sobre el año).
export const CANCIONES = [
// ---------- 1950s ----------
["Rock Around the Clock","Bill Haley & His Comets",1954,"int"],
["Tutti Frutti","Little Richard",1955,"int"],
["Only You (And You Alone)","The Platters",1955,"int"],
["Hound Dog","Elvis Presley",1956,"int"],
["Blue Suede Shoes","Carl Perkins",1956,"int"],
["I Walk the Line","Johnny Cash",1956,"int"],
["Jailhouse Rock","Elvis Presley",1957,"int"],
["Great Balls of Fire","Jerry Lee Lewis",1957,"int"],
["Johnny B. Goode","Chuck Berry",1958,"int"],
["Summertime Blues","Eddie Cochran",1958,"int"],
["La Bamba","Ritchie Valens",1958,"es"],
["What'd I Say","Ray Charles",1959,"int"],
["Mack the Knife","Bobby Darin",1959,"int"],
// ---------- 1960s ----------
["El Porompompero","Manolo Escobar",1960,"es"],
["At Last","Etta James",1960,"int"],
["Stand by Me","Ben E. King",1961,"int"],
["Runaway","Del Shannon",1961,"int"],
["Cuando calienta el sol","Los Hermanos Rigual",1962,"es"],
["She Loves You","The Beatles",1963,"int"],
["Surfin' U.S.A.","The Beach Boys",1963,"int"],
["I Want to Hold Your Hand","The Beatles",1963,"int"],
["Twist and Shout","The Beatles",1963,"int"],
["The House of the Rising Sun","The Animals",1964,"int"],
["My Girl","The Temptations",1964,"int"],
["Fly Me to the Moon","Frank Sinatra",1964,"int"],
["(I Can't Get No) Satisfaction","The Rolling Stones",1965,"int"],
["Like a Rolling Stone","Bob Dylan",1965,"int"],
["California Dreamin'","The Mamas & The Papas",1965,"int"],
["Gracias a la vida","Violeta Parra",1966,"es"],
["Good Vibrations","The Beach Boys",1966,"int"],
["Paint It, Black","The Rolling Stones",1966,"int"],
["Mi limón, mi limonero","Henry Stephen",1967,"es"],
["Respect","Aretha Franklin",1967,"int"],
["Light My Fire","The Doors",1967,"int"],
["A Whiter Shade of Pale","Procol Harum",1967,"int"],
["All You Need Is Love","The Beatles",1967,"int"],
["Purple Haze","Jimi Hendrix",1967,"int"],
["Sunshine of Your Love","Cream",1967,"int"],
["La, la, la","Massiel",1968,"es"],
["Born to Be Wild","Steppenwolf",1968,"int"],
["Hey Jude","The Beatles",1968,"int"],
["(Sittin' On) The Dock of the Bay","Otis Redding",1968,"int"],
["Jumpin' Jack Flash","The Rolling Stones",1968,"int"],
["Sympathy for the Devil","The Rolling Stones",1968,"int"],
["I Heard It Through the Grapevine","Marvin Gaye",1968,"int"],
["Piece of My Heart","Big Brother & The Holding Company",1968,"int"],
["Vivo cantando","Salomé",1969,"es"],
["Cantares","Joan Manuel Serrat",1969,"es"],
["Penélope","Joan Manuel Serrat",1969,"es"],
["Come Together","The Beatles",1969,"int"],
["Here Comes the Sun","The Beatles",1969,"int"],
["Space Oddity","David Bowie",1969,"int"],
["Whole Lotta Love","Led Zeppelin",1969,"int"],
["Fortunate Son","Creedence Clearwater Revival",1969,"int"],
["Bad Moon Rising","Creedence Clearwater Revival",1969,"int"],
["Proud Mary","Creedence Clearwater Revival",1969,"int"],
["Suspicious Minds","Elvis Presley",1969,"int"],
["I Want You Back","The Jackson 5",1969,"int"],
// ---------- 1970s ----------
["Un rayo de sol","Los Diablos",1970,"es"],
["Gwendolyne","Julio Iglesias",1970,"es"],
["Oye cómo va","Santana",1970,"int"],
["Black Magic Woman","Santana",1970,"int"],
["Let It Be","The Beatles",1970,"int"],
["Bridge over Troubled Water","Simon & Garfunkel",1970,"int"],
["Ain't No Mountain High Enough","Diana Ross",1970,"int"],
["Immigrant Song","Led Zeppelin",1970,"int"],
["Your Song","Elton John",1970,"int"],
["Layla","Derek and the Dominos",1970,"int"],
["Big Yellow Taxi","Joni Mitchell",1970,"int"],
["ABC","The Jackson 5",1970,"int"],
["Mediterráneo","Joan Manuel Serrat",1971,"es"],
["América","Nino Bravo",1971,"es"],
["Stairway to Heaven","Led Zeppelin",1971,"int"],
["Imagine","John Lennon",1971,"int"],
["What's Going On","Marvin Gaye",1971,"int"],
["Maggie May","Rod Stewart",1971,"int"],
["American Pie","Don McLean",1971,"int"],
["Ain't No Sunshine","Bill Withers",1971,"int"],
["Tiny Dancer","Elton John",1971,"int"],
["Life on Mars?","David Bowie",1971,"int"],
["Baba O'Riley","The Who",1971,"int"],
["Un beso y una flor","Nino Bravo",1972,"es"],
["Libre","Nino Bravo",1972,"es"],
["Un canto a Galicia","Julio Iglesias",1972,"es"],
["Volver, volver","Vicente Fernández",1972,"es"],
["Lean on Me","Bill Withers",1972,"int"],
["Superstition","Stevie Wonder",1972,"int"],
["Rocket Man","Elton John",1972,"int"],
["Smoke on the Water","Deep Purple",1972,"int"],
["Y viva España","Manolo Escobar",1973,"es"],
["Eres tú","Mocedades",1973,"es"],
["Entre dos aguas","Paco de Lucía",1973,"es"],
["El rey","Vicente Fernández",1973,"es"],
["Money","Pink Floyd",1973,"int"],
["Free Bird","Lynyrd Skynyrd",1973,"int"],
["Dream On","Aerosmith",1973,"int"],
["Quimbara","Celia Cruz & Johnny Pacheco",1974,"es"],
["Waterloo","ABBA",1974,"int"],
["Killer Queen","Queen",1974,"int"],
["Sweet Home Alabama","Lynyrd Skynyrd",1974,"int"],
["Rebel Rebel","David Bowie",1974,"int"],
["No Woman, No Cry","Bob Marley & The Wailers",1974,"int"],
["Hooked on a Feeling","Blue Swede",1974,"int"],
["Mamma Mia","ABBA",1975,"int"],
["Bohemian Rhapsody","Queen",1975,"int"],
["Wish You Were Here","Pink Floyd",1975,"int"],
["Born to Run","Bruce Springsteen",1975,"int"],
["Dancing Queen","ABBA",1976,"int"],
["Fernando","ABBA",1976,"int"],
["Knowing Me, Knowing You","ABBA",1976,"int"],
["Hotel California","Eagles",1976,"int"],
["More Than a Feeling","Boston",1976,"int"],
["Anarchy in the U.K.","Sex Pistols",1976,"int"],
["Carry On Wayward Son","Kansas",1976,"int"],
["We Will Rock You","Queen",1977,"int"],
["We Are the Champions","Queen",1977,"int"],
["Stayin' Alive","Bee Gees",1977,"int"],
["How Deep Is Your Love","Bee Gees",1977,"int"],
["I Feel Love","Donna Summer",1977,"int"],
["God Save the Queen","Sex Pistols",1977,"int"],
["\"Heroes\"","David Bowie",1977,"int"],
["One Love / People Get Ready","Bob Marley & The Wailers",1977,"int"],
["Three Little Birds","Bob Marley & The Wailers",1977,"int"],
["Me olvidé de vivir","Julio Iglesias",1978,"es"],
["Ojalá","Silvio Rodríguez",1978,"es"],
["Pedro Navaja","Rubén Blades & Willie Colón",1978,"es"],
["Plástico","Rubén Blades & Willie Colón",1978,"es"],
["Solo le pido a Dios","León Gieco",1978,"es"],
["Take a Chance on Me","ABBA",1978,"int"],
["Don't Stop Me Now","Queen",1978,"int"],
["I Will Survive","Gloria Gaynor",1978,"int"],
["Le Freak","Chic",1978,"int"],
["Y.M.C.A.","Village People",1978,"int"],
["September","Earth, Wind & Fire",1978,"int"],
["Heart of Glass","Blondie",1978,"int"],
["Roxanne","The Police",1978,"int"],
["Sultans of Swing","Dire Straits",1978,"int"],
["Volando voy","Camarón de la Isla",1979,"es"],
["Gimme! Gimme! Gimme! (A Man After Midnight)","ABBA",1979,"int"],
["Good Times","Chic",1979,"int"],
["Boogie Wonderland","Earth, Wind & Fire",1979,"int"],
["Hot Stuff","Donna Summer",1979,"int"],
["Rapper's Delight","The Sugarhill Gang",1979,"int"],
["Another Brick in the Wall, Part 2","Pink Floyd",1979,"int"],
["Comfortably Numb","Pink Floyd",1979,"int"],
["Highway to Hell","AC/DC",1979,"int"],
["London Calling","The Clash",1979,"int"],
["Message in a Bottle","The Police",1979,"int"],
["Video Killed the Radio Star","The Buggles",1979,"int"],
["Don't Stop 'Til You Get Enough","Michael Jackson",1979,"int"],
// ---------- 1980s ----------
["La chica de ayer","Nacha Pop",1980,"es"],
["Enamorado de la moda juvenil","Radio Futura",1980,"es"],
["Don Diablo","Miguel Bosé",1980,"es"],
["Hey!","Julio Iglesias",1980,"es"],
["Calle Melancolía","Joaquín Sabina",1980,"es"],
["Another One Bites the Dust","Queen",1980,"int"],
["Back in Black","AC/DC",1980,"int"],
["Call Me","Blondie",1980,"int"],
["Super Trouper","ABBA",1980,"int"],
["The Winner Takes It All","ABBA",1980,"int"],
["Could You Be Loved","Bob Marley & The Wailers",1980,"int"],
["Love Will Tear Us Apart","Joy Division",1980,"int"],
["Whip It","Devo",1980,"int"],
["Hoy no me puedo levantar","Mecano",1981,"es"],
["Déjame","Los Secretos",1981,"es"],
["Under Pressure","Queen & David Bowie",1981,"int"],
["Don't Stop Believin'","Journey",1981,"int"],
["Tainted Love","Soft Cell",1981,"int"],
["Just Can't Get Enough","Depeche Mode",1981,"int"],
["Don't You Want Me","The Human League",1981,"int"],
["Bette Davis Eyes","Kim Carnes",1981,"int"],
["Physical","Olivia Newton-John",1981,"int"],
["Bailando","Alaska y los Pegamoides",1982,"es"],
["Me colé en una fiesta","Mecano",1982,"es"],
["Maquillaje","Mecano",1982,"es"],
["Billie Jean","Michael Jackson",1982,"int"],
["Beat It","Michael Jackson",1982,"int"],
["Thriller","Michael Jackson",1982,"int"],
["Africa","Toto",1982,"int"],
["Eye of the Tiger","Survivor",1982,"int"],
["Hungry Like the Wolf","Duran Duran",1982,"int"],
["No controles","Olé Olé",1983,"es"],
["No mires a los ojos de la gente","Golpes Bajos",1983,"es"],
["Every Breath You Take","The Police",1983,"int"],
["Sweet Dreams (Are Made of This)","Eurythmics",1983,"int"],
["Blue Monday","New Order",1983,"int"],
["Girls Just Want to Have Fun","Cyndi Lauper",1983,"int"],
["Total Eclipse of the Heart","Bonnie Tyler",1983,"int"],
["Karma Chameleon","Culture Club",1983,"int"],
["Relax","Frankie Goes to Hollywood",1983,"int"],
["99 Luftballons","Nena",1983,"int"],
["This Charming Man","The Smiths",1983,"int"],
["Sunday Bloody Sunday","U2",1983,"int"],
["Holiday","Madonna",1983,"int"],
["Flashdance... What a Feeling","Irene Cara",1983,"int"],
["Maniac","Michael Sembello",1983,"int"],
["Escuela de calor","Radio Futura",1984,"es"],
["Ni tú ni nadie","Alaska y Dinarama",1984,"es"],
["Amante bandido","Miguel Bosé",1984,"es"],
["Lobo hombre en París","La Unión",1984,"es"],
["Querida","Juan Gabriel",1984,"es"],
["Amor eterno","Rocío Dúrcal",1984,"es"],
["Radio Ga Ga","Queen",1984,"int"],
["Like a Virgin","Madonna",1984,"int"],
["Material Girl","Madonna",1984,"int"],
["Purple Rain","Prince",1984,"int"],
["When Doves Cry","Prince",1984,"int"],
["Careless Whisper","George Michael",1984,"int"],
["Wake Me Up Before You Go-Go","Wham!",1984,"int"],
["Last Christmas","Wham!",1984,"int"],
["Footloose","Kenny Loggins",1984,"int"],
["Shout","Tears for Fears",1984,"int"],
["Ghostbusters","Ray Parker Jr.",1984,"int"],
["Self Control","Laura Branigan",1984,"int"],
["Devuélveme a mi chica","Hombres G",1985,"es"],
["Sufre mamón","Hombres G",1985,"es"],
["Nada personal","Soda Stereo",1985,"es"],
["Agradecido","Rosendo",1985,"es"],
["Take On Me","a-ha",1985,"int"],
["Don't You (Forget About Me)","Simple Minds",1985,"int"],
["Everybody Wants to Rule the World","Tears for Fears",1985,"int"],
["The Power of Love","Huey Lewis and the News",1985,"int"],
["A quién le importa","Alaska y Dinarama",1986,"es"],
["Cruz de navajas","Mecano",1986,"es"],
["Hijo de la luna","Mecano",1986,"es"],
["Venezia","Hombres G",1986,"es"],
["Marta tiene un marcapasos","Hombres G",1986,"es"],
["Insurrección","El Último de la Fila",1986,"es"],
["Persiana americana","Soda Stereo",1986,"es"],
["Lucha de gigantes","Nacha Pop",1986,"es"],
["Cien gaviotas","Duncan Dhu",1986,"es"],
["Hasta que te conocí","Juan Gabriel",1986,"es"],
["Livin' on a Prayer","Bon Jovi",1986,"int"],
["You Give Love a Bad Name","Bon Jovi",1986,"int"],
["Master of Puppets","Metallica",1986,"int"],
["Kiss","Prince",1986,"int"],
["La Isla Bonita","Madonna",1986,"int"],
["The Final Countdown","Europe",1986,"int"],
["There Is a Light That Never Goes Out","The Smiths",1986,"int"],
["Walk This Way","Run-D.M.C. & Aerosmith",1986,"int"],
["Voyage voyage","Desireless",1986,"int"],
["Annabel Lee","Radio Futura",1987,"es"],
["Camino Soria","Gabinete Caligari",1987,"es"],
["Sabor de amor","Danza Invisible",1987,"es"],
["En algún lugar","Duncan Dhu",1987,"es"],
["Ahora te puedes marchar","Luis Miguel",1987,"es"],
["Sweet Child o' Mine","Guns N' Roses",1987,"int"],
["Welcome to the Jungle","Guns N' Roses",1987,"int"],
["I Wanna Dance with Somebody (Who Loves Me)","Whitney Houston",1987,"int"],
["Faith","George Michael",1987,"int"],
["Never Gonna Give You Up","Rick Astley",1987,"int"],
["With or Without You","U2",1987,"int"],
["I Still Haven't Found What I'm Looking For","U2",1987,"int"],
["Smooth Criminal","Michael Jackson",1987,"int"],
["Bad","Michael Jackson",1987,"int"],
["(I've Had) The Time of My Life","Bill Medley & Jennifer Warnes",1987,"int"],
["Push It","Salt-N-Pepa",1987,"int"],
["Ella, elle l'a","France Gall",1987,"int"],
["Mujer contra mujer","Mecano",1988,"es"],
["Un año más","Mecano",1988,"es"],
["La fuerza del destino","Mecano",1988,"es"],
["Como un burro amarrado en la puerta del baile","El Último de la Fila",1988,"es"],
["Rebelión","Joe Arroyo",1988,"es"],
["Paradise City","Guns N' Roses",1988,"int"],
["Where Is My Mind?","Pixies",1988,"int"],
["Straight Outta Compton","N.W.A",1988,"int"],
["Ojalá que llueva café","Juan Luis Guerra y 440",1989,"es"],
["La incondicional","Luis Miguel",1989,"es"],
["Voy a pasármelo bien","Hombres G",1989,"es"],
["Personal Jesus","Depeche Mode",1989,"int"],
["Like a Prayer","Madonna",1989,"int"],
["Fight the Power","Public Enemy",1989,"int"],
// ---------- 1990s ----------
["Entre dos tierras","Héroes del Silencio",1990,"es"],
["Maldito duende","Héroes del Silencio",1990,"es"],
["De música ligera","Soda Stereo",1990,"es"],
["Burbujas de amor","Juan Luis Guerra y 440",1990,"es"],
["La bilirrubina","Juan Luis Guerra y 440",1990,"es"],
["20 de abril","Celtas Cortos",1990,"es"],
["La célula que explota","Caifanes",1990,"es"],
["Rayando el sol","Maná",1990,"es"],
["Thunderstruck","AC/DC",1990,"int"],
["Enjoy the Silence","Depeche Mode",1990,"int"],
["Nothing Compares 2 U","Sinéad O'Connor",1990,"int"],
["Vogue","Madonna",1990,"int"],
["Ojos de gata","Los Secretos",1991,"es"],
["Chiquilla","Seguridad Social",1991,"es"],
["Smells Like Teen Spirit","Nirvana",1991,"int"],
["Enter Sandman","Metallica",1991,"int"],
["Losing My Religion","R.E.M.",1991,"int"],
["Under the Bridge","Red Hot Chili Peppers",1991,"int"],
["Alive","Pearl Jam",1991,"int"],
["El amor después del amor","Fito Páez",1992,"es"],
["Oye mi amor","Maná",1992,"es"],
["Como la flor","Selena",1992,"es"],
["El sitio de mi recreo","Antonio Vega",1992,"es"],
["Y nos dieron las diez","Joaquín Sabina",1992,"es"],
["Come as You Are","Nirvana",1992,"int"],
["Nothing Else Matters","Metallica",1992,"int"],
["November Rain","Guns N' Roses",1992,"int"],
["Jeremy","Pearl Jam",1992,"int"],
["Killing in the Name","Rage Against the Machine",1992,"int"],
["I Will Always Love You","Whitney Houston",1992,"int"],
["Nuthin' but a 'G' Thang","Dr. Dre",1992,"int"],
["Jump Around","House of Pain",1992,"int"],
["Rhythm Is a Dancer","SNAP!",1992,"int"],
["What's Up?","4 Non Blondes",1992,"int"],
["Macarena","Los del Río",1993,"es"],
["Sin documentos","Los Rodríguez",1993,"es"],
["Matador","Los Fabulosos Cadillacs",1993,"es"],
["Vasos vacíos","Los Fabulosos Cadillacs & Celia Cruz",1993,"es"],
["La gota fría","Carlos Vives",1993,"es"],
["So payaso","Extremoduro",1993,"es"],
["Creep","Radiohead",1992,"int"],
["Linger","The Cranberries",1993,"int"],
["Insane in the Brain","Cypress Hill",1993,"int"],
["What Is Love","Haddaway",1993,"int"],
["Mr. Jones","Counting Crows",1993,"int"],
["Loser","Beck",1993,"int"],
["The Rhythm of the Night","Corona",1993,"int"],
["Lamento boliviano","Enanitos Verdes",1994,"es"],
["Mariposa Tecknicolor","Fito Páez",1994,"es"],
["La Ingrata","Café Tacvba",1994,"es"],
["Afuera","Caifanes",1994,"es"],
["Amor prohibido","Selena",1994,"es"],
["Bidi Bidi Bom Bom","Selena",1994,"es"],
["Black Hole Sun","Soundgarden",1994,"int"],
["Zombie","The Cranberries",1994,"int"],
["Basket Case","Green Day",1994,"int"],
["Self Esteem","The Offspring",1994,"int"],
["Sabotage","Beastie Boys",1994,"int"],
["Juicy","The Notorious B.I.G.",1994,"int"],
["Live Forever","Oasis",1994,"int"],
["Hallelujah","Jeff Buckley",1994,"int"],
["Kiss from a Rose","Seal",1994,"int"],
["Cotton Eye Joe","Rednex",1994,"int"],
["Saturday Night","Whigfield",1994,"int"],
["Estoy aquí","Shakira",1995,"es"],
["Antología","Shakira",1995,"es"],
["Mucho mejor","Los Rodríguez",1995,"es"],
["Mal bicho","Los Fabulosos Cadillacs",1995,"es"],
["La chispa adecuada","Héroes del Silencio",1995,"es"],
["Experiencia religiosa","Enrique Iglesias",1995,"es"],
["Wonderwall","Oasis",1995,"int"],
["Don't Look Back in Anger","Oasis",1995,"int"],
["Gangsta's Paradise","Coolio",1995,"int"],
["California Love","2Pac",1995,"int"],
["Waterfalls","TLC",1995,"int"],
["Born Slippy .NUXX","Underworld",1995,"int"],
["Da Funk","Daft Punk",1995,"int"],
["La flaca","Jarabe de Palo",1996,"es"],
["El talismán","Rosana",1996,"es"],
["Sin miedo","Rosana",1996,"es"],
["Lo echamos a suertes","Ella Baila Sola",1996,"es"],
["Contigo","Joaquín Sabina",1996,"es"],
["Wannabe","Spice Girls",1996,"int"],
["Say You'll Be There","Spice Girls",1996,"int"],
["Firestarter","The Prodigy",1996,"int"],
["Breathe","The Prodigy",1996,"int"],
["Corazón partío","Alejandro Sanz",1997,"es"],
["Y, ¿si fuera ella?","Alejandro Sanz",1997,"es"],
["Flaca","Andrés Calamaro",1997,"es"],
["Loco","Andrés Calamaro",1997,"es"],
["Clavado en un bar","Maná",1997,"es"],
["Morena mía","Miguel Bosé",2001,"es"],
["No estamos lokos","Ketama",1995,"es"],
["Karma Police","Radiohead",1997,"int"],
["No Surprises","Radiohead",1997,"int"],
["Song 2","Blur",1997,"int"],
["Bitter Sweet Symphony","The Verve",1997,"int"],
["Good Riddance (Time of Your Life)","Green Day",1997,"int"],
["Everlong","Foo Fighters",1997,"int"],
["Hypnotize","The Notorious B.I.G.",1997,"int"],
["My Heart Will Go On","Céline Dion",1997,"int"],
["Torn","Natalie Imbruglia",1997,"int"],
["Barbie Girl","Aqua",1997,"int"],
["Around the World","Daft Punk",1997,"int"],
["Everybody (Backstreet's Back)","Backstreet Boys",1997,"int"],
["Semi-Charmed Life","Third Eye Blind",1997,"int"],
["Ciega, sordomuda","Shakira",1998,"es"],
["Ojos así","Shakira",1998,"es"],
["Amiga mía","Alejandro Sanz",1998,"es"],
["Depende","Jarabe de Palo",1998,"es"],
["Clandestino","Manu Chao",1998,"es"],
["La playa","La Oreja de Van Gogh",1998,"es"],
["Molinos de viento","Mägo de Oz",1998,"es"],
["Pájaros de barro","Manolo García",1998,"es"],
["La vida es un carnaval","Celia Cruz",1998,"es"],
["Suavemente","Elvis Crespo",1998,"es"],
["Pretty Fly (For a White Guy)","The Offspring",1998,"int"],
["...Baby One More Time","Britney Spears",1998,"int"],
["Believe","Cher",1998,"int"],
["Changes","2Pac",1998,"int"],
["Doo Wop (That Thing)","Lauryn Hill",1998,"int"],
["Praise You","Fatboy Slim",1998,"int"],
["The Rockafeller Skank","Fatboy Slim",1998,"int"],
["Teardrop","Massive Attack",1998,"int"],
["Iris","Goo Goo Dolls",1998,"int"],
["Blue (Da Ba Dee)","Eiffel 65",1998,"int"],
["La raja de tu falda","Estopa",1999,"es"],
["Tu calorro","Estopa",1999,"es"],
["19 días y 500 noches","Joaquín Sabina",1999,"es"],
["Bailamos","Enrique Iglesias",1999,"es"],
["Livin' la Vida Loca","Ricky Martin",1999,"es"],
["Corazón espinado","Santana & Maná",1999,"es"],
["Californication","Red Hot Chili Peppers",1999,"int"],
["Scar Tissue","Red Hot Chili Peppers",1999,"int"],
["I Want It That Way","Backstreet Boys",1999,"int"],
["Genie in a Bottle","Christina Aguilera",1999,"int"],
["No Scrubs","TLC",1999,"int"],
["My Name Is","Eminem",1999,"int"],
["Smooth","Santana feat. Rob Thomas",1999,"int"],
["Sandstorm","Darude",1999,"int"],
["All the Small Things","blink-182",1999,"int"],
// ---------- 2000s ----------
["Es por ti","Juanes",2000,"es"],
["Fiesta pagana","Mägo de Oz",2000,"es"],
["A puro dolor","Son by Four",2000,"es"],
["Yellow","Coldplay",2000,"int"],
["Ms. Jackson","OutKast",2000,"int"],
["Beautiful Day","U2",2000,"int"],
["Stan","Eminem",2000,"int"],
["The Real Slim Shady","Eminem",2000,"int"],
["Bye Bye Bye","NSYNC",2000,"int"],
["Me gustas tú","Manu Chao",2001,"es"],
["Color esperanza","Diego Torres",2001,"es"],
["Como Camarón","Estopa",2001,"es"],
["Absolutamente","Fangoria",2001,"es"],
["Whenever, Wherever","Shakira",2001,"int"],
["Last Nite","The Strokes",2001,"int"],
["In the End","Linkin Park",2001,"int"],
["Chop Suey!","System of a Down",2001,"int"],
["Clint Eastwood","Gorillaz",2001,"int"],
["The Middle","Jimmy Eat World",2001,"int"],
["Aserejé","Las Ketchup",2002,"es"],
["A Dios le pido","Juanes",2002,"es"],
["Mariposa traicionera","Maná",2002,"es"],
["Sin ti no soy nada","Amaral",2002,"es"],
["Obsesión","Aventura",2002,"es"],
["Ave María","David Bisbal",2002,"es"],
["Clocks","Coldplay",2002,"int"],
["The Scientist","Coldplay",2002,"int"],
["Lose Yourself","Eminem",2002,"int"],
["Without Me","Eminem",2002,"int"],
["Complicated","Avril Lavigne",2002,"int"],
["Sk8er Boi","Avril Lavigne",2002,"int"],
["Hot in Herre","Nelly",2002,"int"],
["Cry Me a River","Justin Timberlake",2002,"int"],
["Beautiful","Christina Aguilera",2002,"int"],
["Rosas","La Oreja de Van Gogh",2003,"es"],
["Puedes contar conmigo","La Oreja de Van Gogh",2003,"es"],
["Bonito","Jarabe de Palo",2003,"es"],
["Peter Pan","El Canto del Loco",2003,"es"],
["Andar conmigo","Julieta Venegas",2003,"es"],
["Eres","Café Tacvba",2003,"es"],
["Son de amores","Andy y Lucas",2003,"es"],
["Con la luna llena","Melendi",2003,"es"],
["Hey Ya!","OutKast",2003,"int"],
["Crazy in Love","Beyoncé",2003,"int"],
["In da Club","50 Cent",2003,"int"],
["Seven Nation Army","The White Stripes",2003,"int"],
["Numb","Linkin Park",2003,"int"],
["Bring Me to Life","Evanescence",2003,"int"],
["Toxic","Britney Spears",2003,"int"],
["Where Is the Love?","The Black Eyed Peas",2003,"int"],
["Mad World","Gary Jules",2003,"int"],
["La camisa negra","Juanes",2004,"es"],
["Bulería","David Bisbal",2004,"es"],
["Gasolina","Daddy Yankee",2004,"es"],
["Ella","Bebe",2004,"es"],
["Malo","Bebe",2004,"es"],
["Vino tinto","Estopa",2004,"es"],
["Tocado y hundido","Melendi",2004,"es"],
["Valió la pena","Marc Anthony",2004,"es"],
["Yeah!","Usher",2004,"int"],
["Mr. Brightside","The Killers",2004,"int"],
["Somebody Told Me","The Killers",2004,"int"],
["Take Me Out","Franz Ferdinand",2004,"int"],
["Boulevard of Broken Dreams","Green Day",2004,"int"],
["American Idiot","Green Day",2004,"int"],
["Since U Been Gone","Kelly Clarkson",2004,"int"],
["La tortura","Shakira & Alejandro Sanz",2005,"es"],
["Zapatillas","El Canto del Loco",2005,"es"],
["La Madre de José","El Canto del Loco",2005,"es"],
["Muñeca de trapo","La Oreja de Van Gogh",2005,"es"],
["Ahí estás tú","Chambao",2005,"es"],
["El universo sobre mí","Amaral",2005,"es"],
["Estrella polar","Pereza",2005,"es"],
["Fix You","Coldplay",2005,"int"],
["Gold Digger","Kanye West",2005,"int"],
["Feel Good Inc.","Gorillaz",2005,"int"],
["Hollaback Girl","Gwen Stefani",2005,"int"],
["I Bet You Look Good on the Dancefloor","Arctic Monkeys",2005,"int"],
["Hung Up","Madonna",2005,"int"],
["Labios compartidos","Maná",2006,"es"],
["Limón y sal","Julieta Venegas",2006,"es"],
["Me voy","Julieta Venegas",2006,"es"],
["Hips Don't Lie","Shakira feat. Wyclef Jean",2006,"int"],
["Crazy","Gnarls Barkley",2006,"int"],
["Rehab","Amy Winehouse",2006,"int"],
["Back to Black","Amy Winehouse",2006,"int"],
["Chasing Cars","Snow Patrol",2006,"int"],
["SexyBack","Justin Timberlake",2006,"int"],
["Hey There Delilah","Plain White T's",2006,"int"],
["Apologize","OneRepublic",2006,"int"],
["Me enamora","Juanes",2007,"es"],
["La revolución sexual","La Casa Azul",2007,"es"],
["Umbrella","Rihanna",2007,"int"],
["Don't Stop the Music","Rihanna",2007,"int"],
["Stronger","Kanye West",2007,"int"],
["Valerie","Mark Ronson feat. Amy Winehouse",2007,"int"],
["Paper Planes","M.I.A.",2007,"int"],
["Low","Flo Rida feat. T-Pain",2007,"int"],
["505","Arctic Monkeys",2007,"int"],
["Colgando en tus manos","Carlos Baute & Marta Sánchez",2008,"es"],
["Copenhague","Vetusta Morla",2008,"es"],
["Tenía tanto que darte","Nena Daconte",2008,"es"],
["Single Ladies (Put a Ring on It)","Beyoncé",2008,"int"],
["Halo","Beyoncé",2008,"int"],
["Viva la Vida","Coldplay",2008,"int"],
["Poker Face","Lady Gaga",2008,"int"],
["Just Dance","Lady Gaga",2008,"int"],
["Use Somebody","Kings of Leon",2008,"int"],
["Sex on Fire","Kings of Leon",2008,"int"],
["Chasing Pavements","Adele",2008,"int"],
["Love Story","Taylor Swift",2008,"int"],
["Allí donde solíamos gritar","Love of Lesbian",2009,"es"],
["Bad Romance","Lady Gaga",2009,"int"],
["I Gotta Feeling","The Black Eyed Peas",2009,"int"],
["Boom Boom Pow","The Black Eyed Peas",2009,"int"],
["Empire State of Mind","JAY-Z feat. Alicia Keys",2009,"int"],
["Fireflies","Owl City",2009,"int"],
["TiK ToK","Kesha",2009,"int"],
// ---------- 2010s ----------
["Waka Waka (Esto es África)","Shakira",2010,"es"],
["Perdóname","Pablo Alborán",2010,"es"],
["Solamente tú","Pablo Alborán",2010,"es"],
["Danza Kuduro","Don Omar & Lucenzo",2010,"es"],
["Mientes","Camila",2010,"es"],
["Rolling in the Deep","Adele",2010,"int"],
["Firework","Katy Perry",2010,"int"],
["Just the Way You Are","Bruno Mars",2010,"int"],
["Baby","Justin Bieber feat. Ludacris",2010,"int"],
["Pumped Up Kicks","Foster the People",2010,"int"],
["Heat Waves","Glass Animals",2020,"int"],
["Someone Like You","Adele",2011,"int"],
["Set Fire to the Rain","Adele",2011,"int"],
["Party Rock Anthem","LMFAO",2011,"int"],
["Moves like Jagger","Maroon 5 feat. Christina Aguilera",2011,"int"],
["Levels","Avicii",2011,"int"],
["Titanium","David Guetta feat. Sia",2011,"int"],
["Somebody That I Used to Know","Gotye feat. Kimbra",2011,"int"],
["Little Talks","Of Monsters and Men",2011,"int"],
["Call Me Maybe","Carly Rae Jepsen",2012,"int"],
["Gangnam Style","PSY",2012,"int"],
["Radioactive","Imagine Dragons",2012,"int"],
["Locked Out of Heaven","Bruno Mars",2012,"int"],
["Payphone","Maroon 5 feat. Wiz Khalifa",2012,"int"],
["Ho Hey","The Lumineers",2012,"int"],
["I Will Wait","Mumford & Sons",2012,"int"],
["Sweater Weather","The Neighbourhood",2012,"int"],
["Vivir mi vida","Marc Anthony",2013,"es"],
["Propuesta indecente","Romeo Santos",2013,"es"],
["Darte un beso","Prince Royce",2013,"es"],
["Get Lucky","Daft Punk feat. Pharrell Williams",2013,"int"],
["Happy","Pharrell Williams",2013,"int"],
["Wake Me Up","Avicii",2013,"int"],
["Counting Stars","OneRepublic",2013,"int"],
["Royals","Lorde",2013,"int"],
["Roar","Katy Perry",2013,"int"],
["Wrecking Ball","Miley Cyrus",2013,"int"],
["Take Me to Church","Hozier",2013,"int"],
["Riptide","Vance Joy",2013,"int"],
["Do I Wanna Know?","Arctic Monkeys",2013,"int"],
["Rude","MAGIC!",2013,"int"],
["Bailando","Enrique Iglesias feat. Descemer Bueno & Gente de Zona",2014,"es"],
["Ay Vamos","J Balvin",2014,"es"],
["Uptown Funk","Mark Ronson feat. Bruno Mars",2014,"int"],
["Shake It Off","Taylor Swift",2014,"int"],
["Blank Space","Taylor Swift",2014,"int"],
["Chandelier","Sia",2014,"int"],
["Thinking Out Loud","Ed Sheeran",2014,"int"],
["Photograph","Ed Sheeran",2014,"int"],
["Sugar","Maroon 5",2014,"int"],
["Stay with Me","Sam Smith",2014,"int"],
["All of Me","John Legend",2013,"int"],
["Problem","Ariana Grande feat. Iggy Azalea",2014,"int"],
["Cheerleader","OMI",2014,"int"],
["Ginza","J Balvin",2015,"es"],
["Copacabana","Izal",2015,"es"],
["El patio","Pablo López",2015,"es"],
["Can't Feel My Face","The Weeknd",2015,"int"],
["The Hills","The Weeknd",2015,"int"],
["Hotline Bling","Drake",2015,"int"],
["Sorry","Justin Bieber",2015,"int"],
["Love Yourself","Justin Bieber",2015,"int"],
["What Do You Mean?","Justin Bieber",2015,"int"],
["Lean On","Major Lazer & DJ Snake feat. MØ",2015,"int"],
["Faded","Alan Walker",2015,"int"],
["Stitches","Shawn Mendes",2015,"int"],
["Alright","Kendrick Lamar",2015,"int"],
["La bicicleta","Carlos Vives & Shakira",2016,"es"],
["Chantaje","Shakira feat. Maluma",2016,"es"],
["Tu Enemigo","Pablo López feat. Juanes",2016,"es"],
["Closer","The Chainsmokers feat. Halsey",2016,"int"],
["One Dance","Drake",2016,"int"],
["Starboy","The Weeknd feat. Daft Punk",2016,"int"],
["24K Magic","Bruno Mars",2016,"int"],
["Cheap Thrills","Sia",2016,"int"],
["Formation","Beyoncé",2016,"int"],
["Ocean Eyes","Billie Eilish",2016,"int"],
["Despacito","Luis Fonsi & Daddy Yankee",2017,"es"],
["Mi Gente","J Balvin & Willy William",2017,"es"],
["Felices los 4","Maluma",2017,"es"],
["Súbeme la Radio","Enrique Iglesias",2017,"es"],
["Robarte un Beso","Carlos Vives & Sebastián Yatra",2017,"es"],
["Prometo","Pablo Alborán",2017,"es"],
["Shape of You","Ed Sheeran",2017,"int"],
["Perfect","Ed Sheeran",2017,"int"],
["Havana","Camila Cabello feat. Young Thug",2017,"int"],
["HUMBLE.","Kendrick Lamar",2017,"int"],
["rockstar","Post Malone feat. 21 Savage",2017,"int"],
["New Rules","Dua Lipa",2017,"int"],
["Believer","Imagine Dragons",2017,"int"],
["Feel It Still","Portugal. The Man",2017,"int"],
["Malamente","Rosalía",2018,"es"],
["Pienso en tu mirá","Rosalía",2018,"es"],
["Lo Malo","Aitana & Ana Guerra",2018,"es"],
["Sunflower","Post Malone & Swae Lee",2018,"int"],
["thank u, next","Ariana Grande",2018,"int"],
["God's Plan","Drake",2018,"int"],
["SICKO MODE","Travis Scott",2018,"int"],
["Shallow","Lady Gaga & Bradley Cooper",2018,"int"],
["lovely","Billie Eilish & Khalid",2018,"int"],
["Someone You Loved","Lewis Capaldi",2018,"int"],
["Con Altura","Rosalía & J Balvin",2019,"es"],
["Callaíta","Bad Bunny & Tainy",2019,"es"],
["Tusa","KAROL G & Nicki Minaj",2019,"es"],
["Vas a Quedarte","Aitana",2019,"es"],
["Blinding Lights","The Weeknd",2019,"int"],
["Old Town Road","Lil Nas X",2019,"int"],
["bad guy","Billie Eilish",2019,"int"],
["Señorita","Shawn Mendes & Camila Cabello",2019,"int"],
["Dance Monkey","Tones and I",2019,"int"],
["Circles","Post Malone",2019,"int"],
["Don't Start Now","Dua Lipa",2019,"int"],
["7 rings","Ariana Grande",2019,"int"],
["Say So","Doja Cat",2019,"int"],
["Cruel Summer","Taylor Swift",2019,"int"],
// ---------- 2020s ----------
["Hawái","Maluma",2020,"es"],
["Dákiti","Bad Bunny & Jhay Cortez",2020,"es"],
["Yo Perreo Sola","Bad Bunny",2020,"es"],
["Bichota","KAROL G",2020,"es"],
["Levitating","Dua Lipa",2020,"int"],
["Save Your Tears","The Weeknd",2020,"int"],
["Dynamite","BTS",2020,"int"],
["Tú me dejaste de querer","C. Tangana",2021,"es"],
["Todo de Ti","Rauw Alejandro",2021,"es"],
["Pepas","Farruko",2021,"es"],
["Tacones Rojos","Sebastián Yatra",2021,"es"],
["STAY","The Kid LAROI & Justin Bieber",2021,"int"],
["drivers license","Olivia Rodrigo",2021,"int"],
["good 4 u","Olivia Rodrigo",2021,"int"],
["MONTERO (Call Me By Your Name)","Lil Nas X",2021,"int"],
["INDUSTRY BABY","Lil Nas X & Jack Harlow",2021,"int"],
["Butter","BTS",2021,"int"],
["Bad Habits","Ed Sheeran",2021,"int"],
["Shivers","Ed Sheeran",2021,"int"],
["Woman","Doja Cat",2021,"int"],
["Enemy","Imagine Dragons & JID",2021,"int"],
["abcdefu","GAYLE",2021,"int"],
["Quevedo: Bzrp Music Sessions, Vol. 52","Bizarrap & Quevedo",2022,"es"],
["Tití Me Preguntó","Bad Bunny",2022,"es"],
["Me Porto Bonito","Bad Bunny & Chencho Corleone",2022,"es"],
["Despechá","Rosalía",2022,"es"],
["Provenza","KAROL G",2022,"es"],
["La Bachata","Manuel Turizo",2022,"es"],
["Ateo","C. Tangana & Nathy Peluso",2022,"es"],
["Calm Down","Rema",2022,"int"],
["As It Was","Harry Styles",2022,"int"],
["Anti-Hero","Taylor Swift",2022,"int"],
["Unholy","Sam Smith & Kim Petras",2022,"int"],
["About Damn Time","Lizzo",2022,"int"],
["Kill Bill","SZA",2022,"int"],
["Snooze","SZA",2022,"int"],
["I Ain't Worried","OneRepublic",2022,"int"],
["Made You Look","Meghan Trainor",2022,"int"],
["Shakira: Bzrp Music Sessions, Vol. 53","Bizarrap & Shakira",2023,"es"],
["Ella Baila Sola","Eslabon Armado & Peso Pluma",2023,"es"],
["Flowers","Miley Cyrus",2023,"int"],
["vampire","Olivia Rodrigo",2023,"int"],
["Paint The Town Red","Doja Cat",2023,"int"],
["Cupid","FIFTY FIFTY",2023,"int"],
["Seven","Jung Kook feat. Latto",2023,"int"],
["Si Antes Te Hubiera Conocido","KAROL G",2024,"es"],
["Gata Only","FloyyMenor & Cris MJ",2024,"es"],
["Espresso","Sabrina Carpenter",2024,"int"],
["Please Please Please","Sabrina Carpenter",2024,"int"],
["Not Like Us","Kendrick Lamar",2024,"int"],
["BIRDS OF A FEATHER","Billie Eilish",2024,"int"],
["LUNCH","Billie Eilish",2024,"int"],
["Beautiful Things","Benson Boone",2024,"int"],
["Die With A Smile","Lady Gaga & Bruno Mars",2024,"int"],
["APT.","ROSÉ & Bruno Mars",2024,"int"],
["TEXAS HOLD 'EM","Beyoncé",2024,"int"],
["luther","Kendrick Lamar & SZA",2024,"int"],
["NUEVAYoL","Bad Bunny",2025,"es"],
["DtMF","Bad Bunny",2025,"es"],
["Ordinary","Alex Warren",2025,"int"],
["Golden","HUNTR/X",2025,"int"],
];
